/* Create model */
/* Predict with model */
SELECT * FROM `transformed_record`, LATERAL TABLE(
ML_PREDICT(
      'frauddetection',
      TransactionID,
      TransactionDT,
      TransactionAmt,
      ProductCD,
      card1,
      card2,
      card3,
      card4,
      card5,
      card6,
      addr1,
      addr2,
      P_emaildomain,
      C1,
      C2,
      C3,
      C4,
      C5,
      C6,
      C7,
      C8,
      C9,
      C10,
      C11,
      C12,
      C13,
      C14,
      D1,
      D4,
      D10,
      D15,
      M6,
      V12,
      V13,
      V14,
      V15,
      V16,
      V17,
      V18,
      V19,
      V20,
      V21,
      V22,
      V23,
      V24,
      V25,
      V26,
      V27,
      V28,
      V29,
      V30,
      DT_D,
      DT_W,
      DT_M,
      id_01,
      id_02,
      id_05,
      id_06,
      id_11,
      id_12,
      id_13,
      id_15,
      id_16,
      id_17,
      id_19,
      id_20,
      id_28,
      id_29,
      id_31,
      id_35,
      id_36,
      id_37,
      id_38,
      DeviceType,
      DeviceInfo
    )
)

CREATE MODEL `frauddetection`
INPUT (
    TransactionID INT NOT NULL,
    TransactionAmt FLOAT,
    ProductCD STRING NOT NULL,
    card1 INT,
    card2 FLOAT,
    card3 FLOAT,
    card4 STRING NOT NULL,
    card5 FLOAT,
    card6 STRING NOT NULL,
    addr1 FLOAT,
    addr2 FLOAT,
    dist1 FLOAT,
    dist2 FLOAT,
    P_emaildomain STRING NOT NULL,
    C1 FLOAT,
    C2 FLOAT,
    C3 FLOAT,
    C4 FLOAT,
    C5 FLOAT,
    C6 FLOAT,
    C7 FLOAT,
    C8 FLOAT,
    C9 FLOAT,
    C10 FLOAT,
    C11 FLOAT,
    C12 FLOAT,
    C13 FLOAT,
    C14 FLOAT,
    D1 FLOAT,
    D4 FLOAT,
    D10 FLOAT,
    D15 FLOAT,
    M6 STRING NOT NULL,
    V12 FLOAT,
    V13 FLOAT,
    V14 FLOAT, 
    V15 FLOAT,
    V16 FLOAT,
    V17 FLOAT,
    V18 FLOAT,
    V19 FLOAT,
    V20 FLOAT,
    V21 FLOAT,
    V22 FLOAT,
    V23 FLOAT,
    V24 FLOAT,
    V25 FLOAT,
    V26 FLOAT,
    V27 FLOAT,
    V28 FLOAT,
    V29 FLOAT,
    V30 FLOAT,
    //TODO Type?
    DT_D INT,
    DT_W INT,
    DT_M INT,
    id_01 FLOAT,
    id_02 FLOAT,
    id_05 FLOAT,
    id_06 FLOAT,
    id_11 FLOAT,
    id_12 STRING NOT NULL,
    id_13 FLOAT,
    id_15 STRING NOT NULL,
    id_16 STRING NOT NULL,
    id_17 FLOAT,
    id_19 FLOAT,
    id_20 FLOAT,
    id_28 STRING NOT NULL,
    id_29 STRING NOT NULL,
    id_31 STRING NOT NULL,
    id_35 STRING NOT NULL,
    id_36 STRING NOT NULL,
    id_37 STRING NOT NULL,
    id_38 STRING NOT NULL,
    DeviceType STRING NOT NULL,
    DeviceInfo STRING NOT NULL
)
OUTPUT (isFraud INT) /* 0 or 1 */
WITH (
  'provider' = 'azureml',
  'task' = 'classification',
  'azureml.connection' = '<connection-name>'
)

/* Predict with model */
SELECT * FROM `transformed_records`, LATERAL TABLE(
  ML_PREDICT('frauddetection',
    TransactionID,
    TransactionAmt,
    ProductCD,
    card1,
    card2,
    card3,
    card4,
    card5,
    card6,
    addr1,
    addr2,
    dist1,
    dist2,
    P_emaildomain,
    C1,
    C2,
    C3,
    C4,
    C5,
    C6,
    C7,
    C8,
    C9,
    C10,
    C11,
    C12,
    C13,
    C14,
    D1,
    D4,
    D10,
    D15,
    M6,
    V12,
    V13,
    V14,
    V15,
    V16,
    V17,
    V18,
    V19,
    V20,
    V21,
    V22,
    V23,
    V24,
    V25,
    V26,
    V27,
    V28,
    V29,
    V30,
    dayOfYear,
    dayOfWeek,
    `month`,
    id_01,
    id_02,
    id_05,
    id_06,
    id_11,
    id_12,
    id_13,
    id_15,
    id_16,
    id_17,
    id_19,
    id_20,
    id_28,
    id_29,
    id_31,
    id_35,
    id_36,
    id_37,
    id_38,
    DeviceType,
    DeviceInfo
  )
);