/* Create identity Table */
CREATE TABLE identities (
    TransactionID INT NOT NULL,
    id_01 FLOAT,
    id_02 FLOAT,
    id_03 FLOAT,
    id_04 FLOAT,
    id_05 FLOAT,
    id_06 FLOAT,
    id_07 FLOAT,
    id_08 FLOAT,
    id_09 FLOAT,
    id_10 FLOAT,
    id_11 FLOAT,
    id_12 STRING NOT NULL,
    id_13 FLOAT,
    id_14 FLOAT,
    id_15 STRING NOT NULL,
    id_16 STRING NOT NULL,
    id_17 FLOAT,
    id_18 FLOAT,
    id_19 FLOAT,
    id_20 FLOAT,
    id_21 FLOAT,
    id_22 FLOAT,
    id_23 STRING NOT NULL,
    id_24 FLOAT,
    id_25 FLOAT,
    id_26 FLOAT,
    id_27 STRING NOT NULL,
    id_28 STRING NOT NULL,
    id_29 STRING NOT NULL,
    id_30 STRING NOT NULL,
    id_31 STRING NOT NULL,
    id_32 FLOAT,
    id_33 STRING NOT NULL,
    id_34 STRING NOT NULL,
    id_35 STRING NOT NULL,
    id_36 STRING NOT NULL,
    id_37 STRING NOT NULL,
    id_38 STRING NOT NULL,
    DeviceType STRING NOT NULL,
    DeviceInfo STRING NOT NULL,
    TransactionDT FLOAT,
    `Timestamp` TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (TransactionID) NOT ENFORCED,
    WATERMARK FOR `Timestamp` AS `Timestamp` - INTERVAL '20' SECOND
) WITH ('changelog.mode' = 'append');

/* Create trasaction table */
CREATE TABLE transactions (
    TransactionID INT NOT NULL,
    TransactionAmt FLOAT,
    ProductCD STRING NOT NULL,
    card1 INT,
    card2 FLOAT,
    card3 FLOAT,
    card4 STRING NOT NULL,
    card5 FLOAT,
    card6 STRING NOT NULL,
    addr1 FLOAT,
    addr2 FLOAT,
    dist1 FLOAT,
    dist2 FLOAT,
    P_emaildomain STRING NOT NULL,
    R_emaildomain STRING NOT NULL,
    C1 FLOAT,
    C2 FLOAT,
    C3 FLOAT,
    C4 FLOAT,
    C5 FLOAT,
    C6 FLOAT,
    C7 FLOAT,
    C8 FLOAT,
    C9 FLOAT,
    C10 FLOAT,
    C11 FLOAT,
    C12 FLOAT,
    C13 FLOAT,
    C14 FLOAT,
    D1 FLOAT,
    D2 FLOAT,
    D3 FLOAT,
    D4 FLOAT,
    D5 FLOAT,
    D10 FLOAT,
    D11 FLOAT,
    D15 FLOAT,
    M1 STRING NOT NULL,
    M2 STRING NOT NULL,
    M3 STRING NOT NULL,
    M4 STRING NOT NULL,
    M5 STRING NOT NULL,
    M6 STRING NOT NULL,
    M7 STRING NOT NULL,
    M8 STRING NOT NULL,
    M9 STRING NOT NULL,
    V1 FLOAT,
    V2 FLOAT,
    V3 FLOAT,
    V4 FLOAT,
    V5 FLOAT,
    V6 FLOAT,
    V7 FLOAT,
    V8 FLOAT,
    V9 FLOAT,
    V10 FLOAT,
    V11 FLOAT,
    V12 FLOAT,
    V13 FLOAT,
    V14 FLOAT, 
    V15 FLOAT,
    V16 FLOAT,
    V17 FLOAT,
    V18 FLOAT,
    V19 FLOAT,
    V20 FLOAT,
    V21 FLOAT,
    V22 FLOAT,
    V23 FLOAT,
    V24 FLOAT,
    V25 FLOAT,
    V26 FLOAT,
    V27 FLOAT,
    V28 FLOAT,
    V29 FLOAT,
    V30 FLOAT,
    TransactionDT FLOAT NOT NULL,
    `Timestamp` TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (TransactionID) NOT ENFORCED,
    WATERMARK FOR `Timestamp` AS `Timestamp` - INTERVAL '20' SECOND
) WITH ('changelog.mode' = 'append');

/* Join transaction and identity table */
CREATE TABLE `joined_records`AS 
SELECT * 
FROM `transactions` t
LEFT JOIN `identities` i 
ON t.TransactionID = i.TransactionID 
AND i.`Timestamp` BETWEEN t.`Timestamp` - INTERVAL '60' SECOND AND t.`Timestamp`+ INTERVAL '60' SECOND;

/* Add new time-based features */
CREATE TABLE `transformed_records` AS
SELECT 
    event.*,
    EXTRACT(DOY FROM TIMESTAMPADD(SECOND, CAST(`TransactionDT` AS INTEGER), TIMESTAMP '2017-11-30 00:00:00')) AS `dayOfYear`,
    EXTRACT(DOW FROM TIMESTAMPADD(SECOND, CAST(`TransactionDT` AS INTEGER), TIMESTAMP '2017-11-30 00:00:00')) AS `dayOfWeek`,
    EXTRACT(MONTH FROM TIMESTAMPADD(SECOND, CAST(`TransactionDT` AS INTEGER), TIMESTAMP '2017-11-30 00:00:00')) AS `month`
FROM 
    `joined_records` AS event;

/* 
 * Encode all features as a JSON string 
 * (Only needed as a workaround if number of features for model prediction exceeds 84) 
 */
CREATE TABLE `transformed_records_json` AS
SELECT JSON_OBJECT(
    'TransactionID' VALUE T.TransactionID,
    'TransactionDT' VALUE T.TransactionDT,
    'TransactionAmt' VALUE T.TransactionAmt,
    'ProductCD' VALUE T.ProductCD,
    'card1' VALUE T.card1,
    'card2' VALUE T.card2,
    'card3' VALUE T.card3,
    'card4' VALUE T.card4,
    'card5' VALUE T.card5,
    'card6' VALUE T.card6,
    'addr1' VALUE T.addr1,
    'addr2' VALUE T.addr2,
    'P_emaildomain' VALUE T.P_emaildomain,
    'C1' VALUE T.C1,
    'C2' VALUE T.C2,
    'C3' VALUE T.C3,
    'C4' VALUE T.C4,
    'C5' VALUE T.C5,
    'C6' VALUE T.C6,
    'C7' VALUE T.C7,
    'C8' VALUE T.C8,
    'C9' VALUE T.C9,
    'C10' VALUE T.C10,
    'C11' VALUE T.C11,
    'C12' VALUE T.C12,
    'C13' VALUE T.C13,
    'C14' VALUE T.C14,
    'D1' VALUE T.D1,
    'D4' VALUE T.D4,
    'D10' VALUE T.D10,
    'D15' VALUE T.D15,
    'M6' VALUE T.M6,
    'V12' VALUE T.V12,
    'V13' VALUE T.V13,
    'V14' VALUE T.V14,
    'V15' VALUE T.V15,
    'V16' VALUE T.V16,
    'V17' VALUE T.V17,
    'V18' VALUE T.V18,
    'V19' VALUE T.V19,
    'V20' VALUE T.V20,
    'V21' VALUE T.V21,
    'V22' VALUE T.V22,
    'V23' VALUE T.V23,
    'V24' VALUE T.V24,
    'V25' VALUE T.V25,
    'V26' VALUE T.V26,
    'V27' VALUE T.V27,
    'V28' VALUE T.V28,
    'V29' VALUE T.V29,
    'V30' VALUE T.V30,
    'DT_D' VALUE T.dayOfYear,
    'DT_W' VALUE T.dayOfWeek,
    'DT_M' VALUE T.`month`,
    'id_01' VALUE T.id_01,
    'id_02' VALUE T.id_02,
    'id_05' VALUE T.id_05,
    'id_06' VALUE T.id_06,
    'id_11' VALUE T.id_11,
    'id_12' VALUE T.id_12,
    'id_13' VALUE T.id_13,
    'id_15' VALUE T.id_15,
    'id_16' VALUE T.id_16,
    'id_17' VALUE T.id_17,
    'id_19' VALUE T.id_19,
    'id_20' VALUE T.id_20,
    'id_28' VALUE T.id_28,
    'id_29' VALUE T.id_29,
    'id_31' VALUE T.id_31,
    'id_35' VALUE T.id_35,
    'id_36' VALUE T.id_36,
    'id_37' VALUE T.id_37,
    'id_38' VALUE T.id_38,
    'DeviceType' VALUE T.DeviceType,
    'DeviceInfo' VALUE T.DeviceInfo
) AS InputJson
FROM `transformed_records` AS T;
